### ISSUE TITLE
"Creating Visual Feedback" page is incomplete

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-documentation#10]
Is it intentional? 

https://github.com/intechstudio/grid-documentation/blob/7b230c13f4054299ecd298ed781d13823294c245/docs/wiki/feedback.md?plain=1#L15

**Comment by kkerti** [comment]
Hi @giacecco, since the past year we reworked twice the docs site. I'm closing this question of yours, as I think in some capacity the answer can be found on the new docs. Also with the current work on improving midi rx, we'll add more comprehensive guides and info how feedback from software or hardware can be utilised.

Thanks for your continued input across our repositories!
